### ISSUE TITLE
find_all querying

### ISSUE THREAD

**Issue by phated** [dmitrizagidulin/nrj#7]
I am querying a geospatial index with the following code snippet but not getting any results back.

``` js
collection.find_all({
    d: '100000',
    pt: '42,-12',
    sfield: 'location'
}, console.log);
```

with the following data in my collection

``` js
{"location":"42,-12"}
```

Is this the incorrect way to query for geospatial data?

**Comment by dmitrizagidulin** [comment]
Right, that's not quite it. You're on the right track though.

The `find_all()` and `find_one()` (which map to RJ REST resources) expect a JSON query as the input, right? But that JSON object does not translate into a Solr URL query directly. It's actually its own DSL.  So it consists of key/values, but the keys are either field names, or special keywords like `$per_page`, boolean operators, and other related stuff. And there aren't any geospatial keywords or operators implemented.

So instead, you have to make raw queries to Solr yourself, at the moment.
Take a look at what I did here, in ruby:
https://github.com/basho-labs/riak_json_ruby_client/blob/master/test/integration/geo_search_integration_test.rb#L33

There, the query param json object is just an argument I pass to an http transport GET request, which treats them as URL fragments, and passes them directly to solr (see https://github.com/basho-labs/riak_json_ruby_client/blob/master/lib/riak_json/client.rb#L157 ).

(Also, I'm assuming you created a schema for that collection beforehand, and set the 'location' field of type location).

**Comment by phated** [comment]
I noticed in the ruby implementation of `solr_query_raw`, the query is a GET request, but in this implementation, it is a PUT request. I tried switching it to a get request but I get a "method not allowed" response.

**Comment by phated** [comment]
Nevermind, I see that the path has to be `/search` instead of the find_all or find_one path.

**Comment by dmitrizagidulin** [comment]
Yeah, exactly - the query to RiakJson `/document/collection/whatever/query/all` is a PUT request (we've had extensive arguments about this, internally, and settled on PUT). 
But Solr expects a plain GET, to its `/search` resource.
Closing, unless you have other questions.
